### ISSUE TITLE
typo: "repostitory" should be "repository" in about

### ISSUE THREAD

**Issue by Beliavsky** [urbanjost/easy#1]
I look forward to trying your project and learning to use git.

**Comment by urbanjost** [comment]
Just playing with the concept at this point, but thanks for the interest; it is motivating. Lots of others have put effort into making fpm callable from github actions, the ford(1) document generator  (or doxygen) can save a lot of effort in creating developer documentation, things like unit testing and changelogs are usually considered good practice, and of course version control and collaborative sites and fpm are all great but I found it personally painful to gather up enough info to put it all to good use initially, so I was thinking an fpm plugin that could prompt you through getting setup would have been really nice to have had. I am thinking that is were this could lead, but in the mean time I am trying to thrash though what the pieces should even look like.  98% of my git usage is probably "init, add, commit, push, status, and log"  so beyond those basics I mostly planned on just pointing to some other references. The results are likely to be very biased towards where I have gotten, but I think it will be useful to show at least one example of putting all the pieces together.
